dist: focal
language: ruby
rvm: 2.7
before_script:
  - export MODELS_VERSION=0.1.0
  - ./test/ci/install_models.sh
  - export MODELS_PATH=$HOME/models/$MODELS_VERSION
cache:
  bundler: true
  directories:
    - $HOME/models
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
