name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - uses: actions/cache@v2
      with:
        path: models
        key: models-v3
      id: cache-models
    - name: Download models
      if: steps.cache-models.outputs.cache-hit != 'true'
      run: |
        mkdir models
        cd models
        wget -q https://github.com/ankane/informers/releases/download/v0.1.0/sentiment-analysis.onnx
        wget -q https://github.com/ankane/informers/releases/download/v0.1.0/question-answering.onnx
        wget -q https://github.com/ankane/informers/releases/download/v0.1.0/feature-extraction.onnx
    - run: bundle exec rake test
      env:
        MODELS_PATH: models
