name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          path: models
          key: models-v3
        id: cache-models
      - name: Download models
        if: steps.cache-models.outputs.cache-hit != 'true'
        run: |
          mkdir models
          cd models
          wget -q https://github.com/ankane/informers/releases/download/v0.1.0/sentiment-analysis.onnx
          wget -q https://github.com/ankane/informers/releases/download/v0.1.0/question-answering.onnx
          wget -q https://github.com/ankane/informers/releases/download/v0.1.0/feature-extraction.onnx
      - run: bundle exec rake test
        env:
          MODELS_PATH: models
