name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - uses: actions/cache@v4
        with:
          path: ~/.cache/informers
          key: informers
      - run: sudo apt-get update && sudo apt-get install libvips
      - run: bundle exec rake download:files
      - run: bundle exec rake test
